### ISSUE TITLE
fitbit doesn't support consumer key any more

### ISSUE THREAD

**Issue by everydaynerd** [tantalor/fitsync#10]
Looks like we cannot get consumer key's anymore:

https://community.fitbit.com/t5/Web-API/OAuth-1-0a-removal-update/m-p/1272107#U1272107

**Comment by Csega** [comment]
I have no deep knowledge about the topic. But does what is the problem with OAuth 2.0 compared to OAuth 1.0a? Something similar should be in the system, shouldn't it? Does this help? http://stackoverflow.com/questions/11744772/does-oauth-2-0-need-consumer-key-consumer-secret

**Comment by rickysarraf** [comment]
Even the library that you depend on has changed. The latest release's interface no more matches with what you are using.

```
rrs@learner:~/.rrs-home/devel/fitsync (master)$ python auth_fitbit.py XXXXXX xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Traceback (most recent call last):
  File "auth_fitbit.py", line 39, in <module>
    from fitbit.api import FitbitOauthClient
ImportError: cannot import name FitbitOauthClient
2016-05-09 / 19:42:07 ♒♒♒  ☹  => 1  
```
